/*
agent/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agent

import (
	"encoding/json"
)

// checks if the AgentListAgentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentListAgentsRequest{}

// AgentListAgentsRequest struct for AgentListAgentsRequest
type AgentListAgentsRequest struct {
	PageToken *string `json:"pageToken,omitempty"`
	Sorts []ListRequestSort `json:"sorts,omitempty"`
	FiltersMask *string `json:"filtersMask,omitempty"`
	Filters *ListRequestFilters `json:"filters,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AgentListAgentsRequest AgentListAgentsRequest

// NewAgentListAgentsRequest instantiates a new AgentListAgentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentListAgentsRequest() *AgentListAgentsRequest {
	this := AgentListAgentsRequest{}
	return &this
}

// NewAgentListAgentsRequestWithDefaults instantiates a new AgentListAgentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentListAgentsRequestWithDefaults() *AgentListAgentsRequest {
	this := AgentListAgentsRequest{}
	return &this
}

// GetPageToken returns the PageToken field value if set, zero value otherwise.
func (o *AgentListAgentsRequest) GetPageToken() string {
	if o == nil || IsNil(o.PageToken) {
		var ret string
		return ret
	}
	return *o.PageToken
}

// GetPageTokenOk returns a tuple with the PageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentListAgentsRequest) GetPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.PageToken) {
		return nil, false
	}
	return o.PageToken, true
}

// HasPageToken returns a boolean if a field has been set.
func (o *AgentListAgentsRequest) HasPageToken() bool {
	if o != nil && !IsNil(o.PageToken) {
		return true
	}

	return false
}

// SetPageToken gets a reference to the given string and assigns it to the PageToken field.
func (o *AgentListAgentsRequest) SetPageToken(v string) {
	o.PageToken = &v
}

// GetSorts returns the Sorts field value if set, zero value otherwise.
func (o *AgentListAgentsRequest) GetSorts() []ListRequestSort {
	if o == nil || IsNil(o.Sorts) {
		var ret []ListRequestSort
		return ret
	}
	return o.Sorts
}

// GetSortsOk returns a tuple with the Sorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentListAgentsRequest) GetSortsOk() ([]ListRequestSort, bool) {
	if o == nil || IsNil(o.Sorts) {
		return nil, false
	}
	return o.Sorts, true
}

// HasSorts returns a boolean if a field has been set.
func (o *AgentListAgentsRequest) HasSorts() bool {
	if o != nil && !IsNil(o.Sorts) {
		return true
	}

	return false
}

// SetSorts gets a reference to the given []ListRequestSort and assigns it to the Sorts field.
func (o *AgentListAgentsRequest) SetSorts(v []ListRequestSort) {
	o.Sorts = v
}

// GetFiltersMask returns the FiltersMask field value if set, zero value otherwise.
func (o *AgentListAgentsRequest) GetFiltersMask() string {
	if o == nil || IsNil(o.FiltersMask) {
		var ret string
		return ret
	}
	return *o.FiltersMask
}

// GetFiltersMaskOk returns a tuple with the FiltersMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentListAgentsRequest) GetFiltersMaskOk() (*string, bool) {
	if o == nil || IsNil(o.FiltersMask) {
		return nil, false
	}
	return o.FiltersMask, true
}

// HasFiltersMask returns a boolean if a field has been set.
func (o *AgentListAgentsRequest) HasFiltersMask() bool {
	if o != nil && !IsNil(o.FiltersMask) {
		return true
	}

	return false
}

// SetFiltersMask gets a reference to the given string and assigns it to the FiltersMask field.
func (o *AgentListAgentsRequest) SetFiltersMask(v string) {
	o.FiltersMask = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *AgentListAgentsRequest) GetFilters() ListRequestFilters {
	if o == nil || IsNil(o.Filters) {
		var ret ListRequestFilters
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentListAgentsRequest) GetFiltersOk() (*ListRequestFilters, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *AgentListAgentsRequest) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given ListRequestFilters and assigns it to the Filters field.
func (o *AgentListAgentsRequest) SetFilters(v ListRequestFilters) {
	o.Filters = &v
}

func (o AgentListAgentsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentListAgentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageToken) {
		toSerialize["pageToken"] = o.PageToken
	}
	if !IsNil(o.Sorts) {
		toSerialize["sorts"] = o.Sorts
	}
	if !IsNil(o.FiltersMask) {
		toSerialize["filtersMask"] = o.FiltersMask
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AgentListAgentsRequest) UnmarshalJSON(data []byte) (err error) {
	varAgentListAgentsRequest := _AgentListAgentsRequest{}

	err = json.Unmarshal(data, &varAgentListAgentsRequest)

	if err != nil {
		return err
	}

	*o = AgentListAgentsRequest(varAgentListAgentsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pageToken")
		delete(additionalProperties, "sorts")
		delete(additionalProperties, "filtersMask")
		delete(additionalProperties, "filters")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *AgentListAgentsRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *AgentListAgentsRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableAgentListAgentsRequest struct {
	value *AgentListAgentsRequest
	isSet bool
}

func (v NullableAgentListAgentsRequest) Get() *AgentListAgentsRequest {
	return v.value
}

func (v *NullableAgentListAgentsRequest) Set(val *AgentListAgentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentListAgentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentListAgentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentListAgentsRequest(val *AgentListAgentsRequest) *NullableAgentListAgentsRequest {
	return &NullableAgentListAgentsRequest{value: val, isSet: true}
}

func (v NullableAgentListAgentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentListAgentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


